services:
  postgres:
    image: postgres:16
    container_name: your-site-postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-admin}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-password}
      - POSTGRES_DB=your_site_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
